/* A small curated library of well-known openings for teaching purposes.
   `moves` are mainline theory SAN strings, replayed via replayIntoEngine
   the same way shared games are — so they're validated against whatever
   the engine actually generates, not just typed by hand and trusted.
   `steps[i]` describes the move that was just played to reach the position
   after moves[i], at a beginner level (no notation jargon beyond the move
   itself, one core idea per step). */

export const OPENINGS = [
  {
    id: "italian",
    name: "Italian Game",
    eco: "C50",
    summary: "Fast, natural development aimed straight at f7.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6"],
    steps: [
      "White claims the center with the king's pawn — e4 is the single most fought-over square in chess openings.",
      "Black mirrors White, fighting for the same central squares rather than conceding them.",
      "White develops a knight toward the center, attacking Black's e5 pawn and preparing to castle.",
      "Black defends e5 and brings out a piece of their own — meet development with development.",
      "The bishop swings to c4, aiming straight down the diagonal at f7 — the only square defended solely by Black's king.",
      "Black develops symmetrically, eyeing the same weak spot on White's side (f2).",
      "White prepares d4, planning to build an even bigger pawn center before Black can react.",
      "Black develops the last knight and adds pressure on White's e4 pawn.",
    ],
  },
  {
    id: "ruy-lopez",
    name: "Ruy Lopez (Spanish)",
    eco: "C60",
    summary: "One of the oldest openings — a quiet pin with long-term pressure.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6"],
    steps: [
      "White stakes a claim in the center — control the middle of the board first.",
      "Black responds in kind, refusing to give White the center for free.",
      "The knight develops and attacks e5, a recurring idea in open games.",
      "Black defends the pawn by developing a piece toward the center.",
      "The bishop pins the knight that's defending e5 — pressure Black will have to deal with sooner or later.",
      "Black asks the question immediately: the bishop must decide whether to trade, retreat, or hold the pin.",
      "White keeps the pin alive by retreating rather than trading — the hallmark move of the Ruy Lopez.",
      "Black develops and attacks e4, forcing White to make a decision about the center.",
    ],
  },
  {
    id: "sicilian",
    name: "Sicilian Defense",
    eco: "B20",
    summary: "Black fights for the center from the side instead of the middle.",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6"],
    steps: [
      "White takes the center.",
      "Instead of mirroring with e5, Black plays on the c-file, aiming for an unbalanced, fighting game rather than a symmetrical one.",
      "White develops naturally and prepares d4, the key central break in most Sicilian lines.",
      "Black supports a future e5 push and opens a line for the dark-squared bishop.",
      "White strikes in the center, offering a pawn trade to open the position.",
      "Black captures — trading a wing pawn for a share of the center is the whole point of the Sicilian.",
      "White recaptures with the knight, landing it on a strong central square.",
      "Black develops, attacking e4 and continuing to fight for the center from the flank.",
    ],
  },
  {
    id: "french",
    name: "French Defense",
    eco: "C00",
    summary: "Solid and slightly cramped at first, but very hard to attack.",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "Bg5", "Be7"],
    steps: [
      "White takes the center.",
      "Black prepares ...d5 without blocking in the dark-squared bishop right away — the defining idea of the French.",
      "White builds an even bigger center.",
      "Black strikes back at the center immediately, challenging White's pawn on e4.",
      "White defends e4 by developing a knight — simple, natural development.",
      "Black develops and adds a second attacker on e4.",
      "White pins the knight, increasing the pressure and preparing to trade off a defender.",
      "Black breaks the pin calmly by developing the last minor piece.",
    ],
  },
  {
    id: "caro-kann",
    name: "Caro-Kann Defense",
    eco: "B10",
    summary: "Like the French, but keeps the light-squared bishop free.",
    moves: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5"],
    steps: [
      "White takes the center.",
      "Black prepares ...d5 while keeping the light-squared bishop's diagonal open — the key difference from the French Defense.",
      "White builds a bigger center.",
      "Black challenges the center at once.",
      "White defends e4 by developing a knight.",
      "Black trades in the center, simplifying the position.",
      "White recaptures with the knight.",
      "Black develops the light-squared bishop actively — the move that gives the Caro-Kann its reputation as a solid, comfortable defense.",
    ],
  },
  {
    id: "queens-gambit",
    name: "Queen's Gambit",
    eco: "D06",
    summary: "A slower, positional opening built around offering a pawn.",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7"],
    steps: [
      "White takes the center with the queen's pawn instead of the king's pawn — a slower, more positional style of opening.",
      "Black meets the center head-on.",
      "White offers a pawn (the 'gambit') to lure Black's d-pawn away from the center — Black doesn't even have to accept it to feel the pressure.",
      "Black declines the gambit and simply develops, keeping the center solid — a completely sound way to meet it.",
      "White develops naturally, adding support to the center.",
      "Black develops and adds pressure toward the center.",
      "White pins the knight, a common idea for increasing central control.",
      "Black breaks the pin with simple development — knights and bishops out before anything fancy.",
    ],
  },
  {
    id: "kings-indian",
    name: "King's Indian Defense",
    eco: "E60",
    summary: "Black lets White take the center, planning to strike back later.",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"],
    steps: [
      "White takes the center.",
      "Black develops a piece first rather than staking a claim in the center immediately — a 'hypermodern' idea: control the center with pieces, not just pawns.",
      "White expands further.",
      "Black prepares to fianchetto the bishop — tucking it on the long diagonal where it eyes the center from a distance.",
      "White develops.",
      "The bishop completes its fianchetto, aiming at White's center from the side.",
      "White grabs even more central space, daring Black to challenge it later.",
      "Black solidifies and prepares to strike back at the center with ...e5 or ...c5 down the road.",
    ],
  },
  {
    id: "london",
    name: "London System",
    eco: "D02",
    summary: "A flexible, low-theory setup White can play against almost anything.",
    moves: ["d4", "d5", "Nf3", "Nf6", "Bf4", "e6", "e3", "Bd6"],
    steps: [
      "White takes the center.",
      "Black meets it symmetrically.",
      "White develops a knight before deciding where the other pieces belong — a flexible, low-theory setup.",
      "Black develops the same way.",
      "White develops the dark-squared bishop outside the pawn chain before playing e3 — the defining move order of the London System, since bishops can get stuck behind their own pawns if played too late.",
      "Black solidifies the center and opens a path for the dark-squared bishop.",
      "White supports the center — now that the bishop is already out, it's safe to close in the pawn.",
      "Black develops and offers a trade of dark-squared bishops.",
    ],
  },
  {
    id: "scholars-mate",
    name: "Scholar's Mate",
    eco: "C20",
    summary: "A classic four-move checkmate trap — a lesson in why f7/f2 matter early on.",
    moves: ["e4", "e5", "Qh5", "Nc6", "Bc4", "Nf6", "Qxf7#"],
    steps: [
      "White takes the center.",
      "Black mirrors White in the center.",
      "White brings the queen out early, eyeing f7 and e5 at the same time — a flashy try that strong players don't fear, but it punishes careless replies.",
      "Black develops a piece and defends e5, but doesn't notice the growing threat against f7 yet.",
      "White adds a second attacker on f7 — now both the queen and bishop are aiming at Black's weakest point.",
      "This natural-looking developing move is actually the losing mistake: it attacks the queen, but leaves f7 completely undefended.",
      "Checkmate! The queen is protected by the bishop on c4, so it can't be captured, and the king has nowhere safe to go. This is exactly why f7 (and f2 for White) needs early attention — it's only defended by the king at the start of the game.",
    ],
  },
  {
    id: "fried-liver",
    name: "Fried Liver Attack",
    eco: "C57",
    summary: "A sharp knight sacrifice that drags the enemy king into the open.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3"],
    steps: [
      "White takes the center.",
      "Black mirrors White.",
      "White develops and attacks e5.",
      "Black defends the pawn and develops.",
      "White develops the bishop, eyeing f7 just like in the Italian Game.",
      "Black develops symmetrically, counterattacking e4 — this move order is called the Two Knights Defense.",
      "White attacks f7 a second time with the knight, ignoring normal development in favor of a direct threat — sharp and aggressive, but risky for both sides.",
      "Black's best response: block the bishop's diagonal and open lines, rather than passively defending f7.",
      "White captures, keeping the attack on f7 alive.",
      "Black recaptures with the knight instead of the queen, keeping the queen safe from future attacks.",
      "The Fried Liver sacrifice: White gives up the knight to drag the black king into the open — this only works because f7 was so lightly defended.",
      "Black is forced to recapture with the king, since nothing else can take the knight — now Black can't castle, and the king is stuck in the center.",
      "White brings the queen out with tempo, checking the exposed king and eyeing the knight on d5 at the same time.",
      "The only way to defend the knight while escaping check — a famous, forced-looking sequence that leaves the black king dangerously exposed.",
      "White develops with another attacker on d5, keeping up the pressure — the whole point of the sacrifice: activity and king safety outweigh the extra material, at least for now.",
    ],
  },
  {
    id: "hyper-accelerated-dragon",
    name: "Hyper-Accelerated Dragon",
    eco: "B27",
    summary: "Reaches the Dragon's fianchetto setup in the fewest possible moves.",
    moves: ["e4", "c5", "Nf3", "g6", "d4", "cxd4", "Nxd4", "Bg7"],
    steps: [
      "White takes the center.",
      "Black strikes back from the side rather than mirroring with e5 — the Sicilian Defense.",
      "White develops naturally, preparing d4.",
      "Instead of the usual ...Nc6 or ...d6 first, Black fianchettoes immediately — this early g6 is what makes it 'hyper-accelerated': reaching the Dragon setup in the fewest possible moves, before committing the other pieces.",
      "White strikes in the center — the standard central break against the Sicilian.",
      "Black captures, trading a wing pawn for central influence, same as in the regular Sicilian — just reached faster here.",
      "White recaptures with the knight, landing it on a strong central square.",
      "The bishop completes its fianchetto, aiming down the long diagonal at White's queenside — the hallmark of every Dragon variation, reached here with maximum flexibility since Black hasn't committed the queenside knight or the d-pawn yet.",
    ],
  },
];
